# Site
name: "রোজনামচা"
description: "প্রোগ্রামিং, কোডিং, ডেভেলপমেন্ট, অ্যান্ড্রয়েড, জাভা, সি, পিএইচপি, ভ্রমণ, সাহিত্য, ঘোরাঘুরি নিয়ে বাংলা ব্লগ"
meta_description: "প্রোগ্রামিং, কোডিং, ডেভেলপমেন্ট, অ্যান্ড্রয়েড, জাভা, সি, পিএইচপি, ভ্রমণ, সাহিত্য, ঘোরাঘুরি নিয়ে বাংলা ব্লগ"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''

# Authors
authors:
  sal:
    name: শান্ত
    display_name: শান্ত
    gravatar: def6db7f821bd4462e2fa8d98871872d
    email: yousuf.hossain.shanto@gmail.com
    web: http://yhshanto.cf
    twitter: 
    description: "ভালোবাসি প্রোগ্রামিং ও গণিতকে। নতুন কিছু নিয়ে ভাবতে, কাজ করতে ভালো লাগে। অ্যাডভেঞ্চার প্রেমী, কিন্তু খুবই অলস"

  john:
    name: শান্ত
    display_name: শান্ত
    gravatar: def6db7f821bd4462e2fa8d98871872d
    email: yousuf.hossain.shanto@gmail.com
    web: http://yhshanto.cf
    twitter: 
    description: "ভালোবাসি প্রোগ্রামিং ও গণিতকে। নতুন কিছু নিয়ে ভাবতে, কাজ করতে ভালো লাগে। অ্যাডভেঞ্চার প্রেমী, কিন্তু খুবই অলস"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge